routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/registerMail/{data}','Auth\RegisterController@index');
// Route::get('/register/{data}','Auth\RegisterController@mailsending');

Route::get('/admin/edit', 'EditProfileController@index')->name('admin-edit');
Route::post('/admin/update/', 'EditProfileController@update')->name('admin-update');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/user/logout', 'Auth\LoginController@userLogout')->name('user.logout');
// --------------------------------------multi auth middleware -----------------------
Route::group(['prefix' => 'admin'], function() {
	Route::group(['middleware' => 'admin.guest'], function(){
		Route::view('/login','admin.login')->name('admin.login');
		Route::post('/login','AdminController@authenticate')->name('admin.auth');
	});
	
	Route::group(['middleware' => 'admin.auth'], function(){
		Route::get('/dashboard','DashboardController@dashboard')->name('admin.dashboard');
        Route::get('/logout', 'AdminController@logout')->name('admin.logout');
	});
});

// ----------------------------------------- crud operation with ajax & simple ------------------------
Route::resource('ajaxemp','EmpAjaxController');
Route::resource('emp','EmpController');

//-------------------------- mail functionality---------------------- 

Route::get('mail', 'HomeController@mail');

Route::get('mailsend', function () {
   
    $details = [
        'title' => 'Mail from system',
        'body' => 'This is for testing email using smtp'
    ];
   
    \Mail::to('rajchetule@gmail.com')->send(new \App\Mail\MyTestMail($details));
   
    dd("Email is Sent.");
});

Route::get('send-mail','MailSend@mailsend');

Route::get('contact','ContactController@index');
Route::post('contact-submit','ContactController@mailsending');

// -------------- payment ===================================================
Route::get('razorpay-payment', 'RazorpayPaymentController@index');
Route::post('razorpay-payment', 'RazorpayPaymentController@store')->name('razorpay.payment.store');

// ============================ multiple delete functionality -=======================
Route::get('/myproducts', 'ProductController@index')->name('products.index');
Route::get('/myproducts/create', 'ProductController@create')->name('products.create');
Route::post('/myproducts/store', 'ProductController@store')->name('products.store');
Route::any('/myproducts/{id}', 'ProductController@destroy')->name('products.delete');
Route::any('myproductsDeleteAll', 'ProductController@deleteAll')->name('products.allDelete');

// ---------relation--------
// Route::get('addItem/{id}', 'ItemController@addItem');
Route::get('item/index/', 'ItemController@index')->name('item.index');
Route::get('item/create', 'ItemController@create')->name('item.create');
Route::post('item/store', 'ItemController@store')->name('item.store');
Route::get('item/changeItemStatus', 'ItemController@changeItemStatus')->name('item.changeItemStatus');

//-----------------item or product category---------------
Route::get('category/index', 'ProductCategoryController@productCategory')->name('category.index');
Route::get('category/create', 'ProductCategoryController@create')->name('category.create');
Route::post('category/store', 'ProductCategoryController@store')->name('category.store');
Route::get('category/edit/{id}', 'ProductCategoryController@edit')->name('category.edit');
Route::post('category/update/{id}', 'ProductCategoryController@update')->name('category.update');
Route::post('category/destroy/{id}', 'ProductCategoryController@destroy')->name('category.destroy');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Item;

class Category extends Model
{
    //
    protected $table = 'categories';

    protected $fillable = [
    'name',
    ];

    public function items(){

        return $this->hasMany('App\Item');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    //
}

resources/views/category/create.blade.php
@extends('layouts.index')
  
@section('content')
<div class="row py-5">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Category</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('category.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif 
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> This Category is already exist<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
   
<form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
     <div class="row ">
        <div class="col-xs-12 col-sm-12 col-md-7">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" id="name" class="form-control"  maxlength="20"  placeholder="Name">
            </div>
        </div>  
        <div class="col-xs-12 col-sm-12 col-md-7 text-left">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        
    </div>
   
</form>


@endsection

resources/views/category/edit.blade.php
@extends('layouts.index')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Category</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('category.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('category.update',$category->id) }}" method="POST">
        @csrf
        {{-- @method('PUT') --}}
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $category->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>   
    </form>
@endsection

resources/views/category/index.blade.php
@extends('layouts.index')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Category list</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('category.create') }}"> Create New Category</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            
            <th width="80px">No</th>
            <th>Product Name</th>
            <th width="270px">Action</th>
        </tr>        
        @foreach($category as $key => $cat)
            <tr>
                
                <td>{{ ++$key }}</td>
                <td>{{ $cat->name }}</td>               
                {{-- <td>{{ $category->name }}</td> --}}
                <td>
                    <form action="{{ route('category.destroy',$cat->id) }}" method="POST">
       
                        {{-- <a class="btn btn-info" href="{{ route('emp.show',$cat->id) }}">View</a> --}}
        
                        <a class="btn btn-primary" href="{{ route('category.edit',$cat->id) }}">Edit</a>
       
                        @csrf
                        {{-- @method('DELETE') --}}
          
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
                
            </tr>
        @endforeach
       
    </table>
</div> 


</body>


      
@endsection