routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/registerMail/{data}','Auth\RegisterController@index');
// Route::get('/register/{data}','Auth\RegisterController@mailsending');

Route::get('/admin/edit', 'EditProfileController@index')->name('admin-edit');
Route::post('/admin/update/', 'EditProfileController@update')->name('admin-update');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/user/logout', 'Auth\LoginController@userLogout')->name('user.logout');
// --------------------------------------multi auth middleware -----------------------
Route::group(['prefix' => 'admin'], function() {
	Route::group(['middleware' => 'admin.guest'], function(){
		Route::view('/login','admin.login')->name('admin.login');
		Route::post('/login','AdminController@authenticate')->name('admin.auth');
	});
	
	Route::group(['middleware' => 'admin.auth'], function(){
		Route::get('/dashboard','DashboardController@dashboard')->name('admin.dashboard');
        Route::get('/logout', 'AdminController@logout')->name('admin.logout');
	});
});

// ----------------------------------------- crud operation with ajax & simple ------------------------
Route::resource('ajaxemp','EmpAjaxController');
Route::resource('emp','EmpController');

//-------------------------- mail functionality---------------------- 

Route::get('mail', 'HomeController@mail');

Route::get('mailsend', function () {
   
    $details = [
        'title' => 'Mail from system',
        'body' => 'This is for testing email using smtp'
    ];
   
    \Mail::to('rajchetule@gmail.com')->send(new \App\Mail\MyTestMail($details));
   
    dd("Email is Sent.");
});

Route::get('send-mail','MailSend@mailsend');

Route::get('contact','ContactController@index');
Route::post('contact-submit','ContactController@mailsending');

// -------------- payment ===================================================
Route::get('razorpay-payment', 'RazorpayPaymentController@index');
Route::post('razorpay-payment', 'RazorpayPaymentController@store')->name('razorpay.payment.store');

// ============================ multiple delete functionality -=======================
Route::get('/myproducts', 'ProductController@index')->name('products.index');
Route::get('/myproducts/create', 'ProductController@create')->name('products.create');
Route::post('/myproducts/store', 'ProductController@store')->name('products.store');
Route::any('/myproducts/{id}', 'ProductController@destroy')->name('products.delete');
Route::any('myproductsDeleteAll', 'ProductController@deleteAll')->name('products.allDelete');

// ---------relation--------
// Route::get('addItem/{id}', 'ItemController@addItem');
Route::get('item/index/', 'ItemController@index')->name('item.index');
Route::get('item/create', 'ItemController@create')->name('item.create');
Route::post('item/store', 'ItemController@store')->name('item.store');
Route::get('item/changeItemStatus', 'ItemController@changeItemStatus')->name('item.changeItemStatus');

//-----------------item or product category---------------
Route::get('category/index', 'ProductCategoryController@productCategory')->name('category.index');
Route::get('category/create', 'ProductCategoryController@create')->name('category.create');
Route::post('category/store', 'ProductCategoryController@store')->name('category.store');
Route::get('category/edit/{id}', 'ProductCategoryController@edit')->name('category.edit');
Route::post('category/update/{id}', 'ProductCategoryController@update')->name('category.update');
Route::post('category/destroy/{id}', 'ProductCategoryController@destroy')->name('category.destroy');

app/Emp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Emp extends Model
{
    protected $fillable = [
        'name', 'post'
    ];
}

app/Http/Controllers/EmpController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Emp;
use Auth;

class EmpController extends Controller
{
    
    public function index()
    {
        
        // dd(Auth::user()->id);
        $emp = Emp::latest()->paginate(5);
  
        return view('emp.index',compact('emp')) ->with('i', (request()->input('page', 1) - 1) * 5);;
    }

    public function create()
    {
        //
        return view('emp.create');
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'post' => 'required',
        ]);
  
        Emp::create($request->all());
   
        return redirect()->route('emp.index')
        ->with('success','Employee created successfully.');
    }

    
    public function show(Emp $emp)
    {
        return view('emp.show',compact('emp'));
    }

    
    public function edit(Emp $emp)
    {
        return view('emp.edit',compact('emp'));
    }
    
    public function update(Request $request, Emp $emp)
    {
        $request->validate([
            'name' => 'required',
            'post' => 'required',
        ]);
  
        $emp->update($request->all());
  
        return redirect()->route('emp.index')
        ->with('success','Employee updated successfully');
    }

    
    public function destroy(Emp $emp)
    {
        
        $emp->delete();
  
        return redirect()->route('emp.index')
        ->with('success','Employee deleted successfully');
    }
}

resources/views/emp/create.blade.php
@extends('emp.layout')
  
@section('content')
<div class="row py-5">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Employee</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('emp.index') }}"> Back</a>
        </div>
    </div>
</div>
   
   
<form action="{{ route('emp.store') }}" method="POST" id="emp-form">
    @csrf
  
     <div class="row ">
        <div class="col-xs-12 col-sm-12 col-md-7">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" id="name" class="form-control" minlength="7" maxlength="15"  placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-7">
            <div class="form-group">
                <strong>Post:</strong>
                <input class="form-control" id="post" name="post" minlength="3" maxlength="10" placeholder="Post" />
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
        
    </div>
   
</form>

<script>
   $(document).ready(function() {
        $("#emp-form").validate({
        rules: {
        name : {
        required: true,
        minlength: 7
        maxlength: 15
        },
        post : {
        required: true,
        minlength: 3
        maxlength: 10
        },
        }
        });
    });
</script>
@endsection

resources/views/emp/edit.blade.php
@extends('emp.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Employee</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('emp.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('emp.update',$emp->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $emp->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Post:</strong>
                    <input class="form-control" style="height:150px" name="post" placeholder="post"{{ $emp->post }} >
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>   
    </form>
@endsection

resources/views/emp/index.blade.php
@extends('emp.layout')
 
@section('content')
    <div class="row pt-5">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 5.8 CRUD Operation</h2>
            </div>
            <div class="pull-right pb-4">
                <a class="btn btn-success" href="{{ route('emp.create') }}"> Create New Employee</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Post</th>
            <th width="270px">Action</th>
        </tr>
        @foreach ($emp as $emp)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $emp->name }}</td>
            <td>{{ $emp->post }}</td>
            <td>
                <form action="{{ route('emp.destroy',$emp->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('emp.show',$emp->id) }}">View</a>
    
                    <a class="btn btn-primary" href="{{ route('emp.edit',$emp->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    
      
@endsection

resources/views/emp/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.8 CRUD Operation</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  
<div class="container">
    @yield('content')



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{{-- 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script> --}}
{{-- 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/additional-methods.js"></script>  --}}

</div>
   
</body>
</html>

resources/views/emp/show.blade.php
@extends('emp.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Employee</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('emp.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $emp->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Post:</strong>
                {{ $emp->post }}
            </div>
        </div>
    </div>
@endsection